# Generated by Django 4.2 on 2023-05-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist_items',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart_items',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist_items',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.product_category'),
            preserve_default=False,
        ),
    ]
