# Generated by Django 4.2 on 2023-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
