# Generated by Django 4.2 on 2023-05-09 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_cart_items_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='cartitem_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='user_order',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now=True)),
                ('star_rank', models.IntegerField()),
                ('product_comment', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_order')),
            ],
        ),
    ]
