# Generated by Django 4.2 on 2023-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
