# Generated by Django 4.2 on 2023-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_address_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bike_type',
            field=models.CharField(choices=[('mountain bike', 'mountain bike'), ('road bik', 'road bike'), ('hybrid', 'hybrid'), ('kids bike', 'kids bike')], max_length=50),
        ),
    ]
