# Generated by Django 4.2 on 2023-05-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_items_cartitem_quantity_user_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='to_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.user_address'),
            preserve_default=False,
        ),
    ]
