# Generated by Django 4.2 on 2023-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_category_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
