# Generated by Django 4.2 on 2023-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bike_type',
            field=models.CharField(choices=[('mountain bike', 'mountain bike'), ('road bike', 'road bike'), ('hybrid bike', 'hybrid bike'), ('kids bike', 'kids bike'), ('ladies bike', 'ladies bike')], max_length=50),
        ),
    ]
