# Generated by Django 4.2 on 2023-05-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_order_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
