# Generated by Django 4.2 on 2023-05-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('home', '0005_customuser_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest_wishlist_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='guest_cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitem_quantity', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product_category')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
        ),
    ]
