# Generated by Django 4.2 on 2023-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('home', '0006_quest_wishlist_items_guest_cart_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quest_wishlist_items',
            new_name='guest_wishlist_items',
        ),
        migrations.AlterField(
            model_name='guest_cart_items',
            name='cartitem_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
