# Generated by Django 4.2 on 2023-05-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_quest_wishlist_items_guest_wishlist_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_wishlist_items',
            old_name='Session_id',
            new_name='session_id',
        ),
    ]
