# Generated by Django 4.2 on 2023-05-13 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_session_id_guest_wishlist_items_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_coupen',
            fields=[
                ('coupen_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coupen_type', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='applyed_coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.discount_coupen')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_order')),
            ],
        ),
    ]
