# Generated by Django 4.2 on 2023-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_discount_coupen_applyed_coupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_order',
            name='coupen_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_order',
            name='mrp_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_order',
            name='payment_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_order',
            name='seller_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
