# Generated by Django 4.2 on 2023-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_user_order_coupen_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
