# Generated by Django 4.2 on 2023-05-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_list_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='canceled_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_cancel', models.TextField()),
                ('payment_return_option', models.CharField(max_length=50)),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user_order')),
            ],
        ),
    ]
